FROM python:3.11

RUN apt-get -qq update
RUN pip install --upgrade pip && pip install pip-tools
RUN apt-get install -y --no-install-recommends g++

WORKDIR /app
COPY . .

RUN pip install -r requirements.txt
