version: "3.9"
services:
  db:
    container_name: flask_postgres
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    hostname: "localhost"
    ports:
      - "5412:5432"
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test
volumes:
  postgres_data:
