version: "3.9"
services:
  db:
    container_name: flask_postgres
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5412:5432"
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test
    expose:
      - 5412
  redis:
    container_name: redis
    image: redis:3.2
    restart: always
    ports:
      - '6379:6379'
    expose:
      - '6379'
    volumes:
      - redis_data:/data
volumes:
  postgres_data:
  redis_data: