"""empty message

Revision ID: 00e153d9375a
Revises: 0dde62cb26e8
Create Date: 2024-03-16 12:11:57.018357

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "00e153d9375a"
down_revision = "0dde62cb26e8"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "events",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(length=100), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "event_user_association",
        sa.Column("event_id", sa.Integer(), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["events.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
    )
    op.drop_table("recipients")
    with op.batch_alter_table("emails", schema=None) as batch_op:
        batch_op.create_foreign_key(None, "events", ["event_id"], ["id"])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("emails", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")

    op.create_table(
        "recipients",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column(
            "email_address", sa.VARCHAR(length=100), autoincrement=False, nullable=False
        ),
        sa.PrimaryKeyConstraint("id", name="recipients_pkey"),
    )
    op.drop_table("event_user_association")
    op.drop_table("users")
    op.drop_table("events")
    # ### end Alembic commands ###
