"""empty message

Revision ID: 02630515db38
Revises: 
Create Date: 2024-03-15 21:46:24.707003

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "02630515db38"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "email",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("event_id", sa.Integer(), nullable=False),
        sa.Column("email_subject", sa.String(length=100), nullable=False),
        sa.Column("email_content", sa.Text(), nullable=False),
        sa.Column("timestamp", sa.DateTime(), nullable=False),
        sa.Column("sent", sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("email")
    # ### end Alembic commands ###
