"""add receipient

Revision ID: 0dde62cb26e8
Revises: 12dbe4282426
Create Date: 2024-03-16 03:21:32.963349

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "0dde62cb26e8"
down_revision = "12dbe4282426"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "recipients",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email_address", sa.String(length=100), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("recipients")
    # ### end Alembic commands ###
