"""empty message

Revision ID: 12dbe4282426
Revises: 02630515db38
Create Date: 2024-03-16 03:17:46.475894

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "12dbe4282426"
down_revision = "02630515db38"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "emails",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("event_id", sa.Integer(), nullable=False),
        sa.Column("email_subject", sa.String(length=100), nullable=False),
        sa.Column("email_content", sa.Text(), nullable=False),
        sa.Column("timestamp", sa.DateTime(), nullable=False),
        sa.Column("sent", sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_table("email")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "email",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("event_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "email_subject", sa.VARCHAR(length=100), autoincrement=False, nullable=False
        ),
        sa.Column("email_content", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column(
            "timestamp", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
        sa.Column("sent", sa.BOOLEAN(), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint("id", name="email_pkey"),
    )
    op.drop_table("emails")
    # ### end Alembic commands ###
